import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavbarMinimal } from "./components/navigation/page";
import { MantineProvider } from "@mantine/core";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <MantineProvider>
          <NavbarMinimal />
          <div className={inter.className} style={{ marginLeft: '80px' }}>
            {children}
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
